spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: asdasdasd
    password: asdasd
    properties:
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls:
            enable: true
  security:
    jwt:
      secret:
        key: asdasd12
      expiration-time: 3600000 # 1 hour in milliseconds
      token-prefix: Bearer
      header-string: Authorization
    oauth2:
      client:
        registration:
          google:
            client-id: asdasd
            client-secret: asdasd
            scope: email,profile,openid
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  server:
    port: 8080
